return {
	["<leader>n"] = {
		name = "NvimTree",
		o = { "<cmd>NvimTreeFocus<cr>", "Focus File Explorer" },
		e = { "<cmd>NvimTreeToggle<cr>", "Toggle File Explorer" },
		f = { "<cmd>NvimTreeFindFile<cr>", "Current File" },
		d = { "<cmd>NvimTreeCollapseKeepBuffers<cr>", "Collapse unopened dir" },
		c = { "<cmd>NvimTreeCollapse<cr>", "Collapse Recursively" },
	},
	["<leader>f"] = {
		name = "Fzf",
		f = { "<cmd>FzfLua files<cr>", "Find files" },
		w = { "<cmd>FzfLua live_grep<cr>", "Find in files" },
		r = { vim.lsp.buf.rename, "Rename" },
	},
	["<leader>b"] = {
		name = "Buffer",
		s = { "<cmd>FzfLua buffers<cr>", "Search" },
		b = { "<cmd>BufferLinePick<cr>", "Select" },
		c = { "<cmd>BufferLinePickClose<cr>", "Close" },
		o = { "<cmd>BufferLineCloseOthers<cr>", "Close Others" },
	},
	["g"] = {
		name = "LSP Actions",
		r = { "<cmd>FzfLua lsp_references<cr>", "References" },
		d = { "<cmd>FzfLua lsp_definitions<cr>", "Definitions" },
		D = { "<cmd>FzfLua lsp_declarations<cr>", "Declarations" },
		I = { "<cmd>FzfLua lsp_implementations<cr>", "Implementations" },
		s = { "<cmd>FzfLua lsp_document_symbols<cr>", "Search symbols" },
	},
	["<leader>l"] = {
		name = "LSP Actions",
		r = { "<cmd>FzfLua lsp_references<cr>", "References" },
		d = { "<cmd>FzfLua lsp_definitions<cr>", "Definitions" },
		D = { "<cmd>FzfLua lsp_declarations<cr>", "Declarations" },
		I = { "<cmd>FzfLua lsp_implementations<cr>", "Implementations" },
		s = { "<cmd>FzfLua lsp_document_symbols<cr>", "Search symbols" },
		a = { "<cmd>FzfLua lsp_code_actions<cr>", "Code Actions" },
	},
	["<leader>d"] = {
		name = "Diagnostics",
		d = { "<cmd>FzfLua diagnostics_document<cr>", "Show file diagnostics" },
		w = { "<cmd>FzfLua diagnostics_workspace<cr>", "Show workspace diagnostics" },
		l = { vim.diagnostic.open_float, "Show line diagnostics" },
		t = { "<cmd>TroubleToggle<cr>", "Trouble" },
	},
	["<leader>t"] = {
		name = "Terminal",
		f = { "<cmd>ToggleTerm direction=float<cr>", "Float" },
		h = { "<cmd>ToggleTerm size=10 direction=horizontal<cr>", "Horizontal" },
		v = { "<cmd>ToggleTerm size=80 direction=vertical<cr>", "Vertical" },
	},
	["<leader>g"] = {
		name = "Git",
		g = { require("anvy.utils.lazygit"), "Lazygit" },
		b = { "<cmd>FzfLua git_branches<cr>", "Branches" },
		t = { "<cmd>FzfLua git_tags<cr>", "Tags" },
		s = { "<cmd>FzfLua git_status<cr>", "Status" },
		c = { "<cmd>FzfLua git_commits<cr>", "Commits" },
		S = { "<cmd>FzfLua git_stash<cr>", "Stash" },
	},
	["<leader>s"] = {
		name = "Session",
		s = { require("resession").save, "Save" },
		l = { require("resession").load, "Load" },
		d = { require("resession").delete, "Delete" },
	},
	["<leader>m"] = {
		name = "Misc",
		k = { "<cmd>FzfLua keymaps<cr>", "Keymaps" },
		t = { "<cmd>FzfLua colorschemes<cr>", "Colorschemes" },
	},
	["<C-j>"] = { "<cmd>SmartCursorMoveLeft<cr>", "Move Left" },
	["<C-l>"] = { "<cmd>SmartCursorMoveRight<cr>", "Move Right" },
	["<leader>c"] = { "<cmd>bdelete<cr>", "CloseBuffer" },
}
